### ISSUE TITLE
Пометка постов прочитанными

### ISSUE THREAD

**Issue by mrChOP93** [Talkvio/talkvio-public#11]
Было бы здорово, если бы посты, просмотренные в ленте, то же помечались прочитанными

**Comment by DEgITx** [comment]
Вот тут не помешает расшифровка, а что значит прочитанные?

**Comment by mrChOP93** [comment]
Что бы скрывались из ленты
![image](https://github.com/Talkvio/talkvio-public/assets/65346358/c2381063-86c5-494b-8252-90ea2ea07f93)

**Comment by DEgITx** [comment]
вроде как сделано же
