### ISSUE TITLE
Порядок вставки изображений в комментарии

### ISSUE THREAD

**Issue by mrChOP93** [Talkvio/talkvio-public#12]
Поменять порядок вставки изображений. На данный момент, изображения вставляются вверху списка, а удобнее было бы, что бы они были внизу.

**Comment by DEgITx** [comment]
Тут опять нужна расшифровка или более детальное описание, не понимаю что означает внизу в данном контексте. вставка через ctrlv или через добавление текстовым блоком или переносом курсором всегда добавляет блок с изображением вниз.
