### ISSUE TITLE
Активация при регистрации (500 Internal Server Error)

### ISSUE THREAD

**Issue by Alien-ufo** [Talkvio/talkvio-public#13]
Использую 2 аккаунта в хроме.
Последовательность:
- в основном аккаунте производим регистрацию
- указываем email 2го акка
- переходим во 2й акк
- открываем почту и письмо с ссылкой активации
- кликаем по ссылке активации
- 500 Internal Server Error

Если вернуться в основной акк и в новой вкладке открыть ссылку - всё ок.

**Comment by DEgITx** [comment]
скорее всего вы открыли неверную ссылку, может почта ее исказила, какую ссылку вы получили?

**Comment by Alien-ufo** [comment]
1) ссылка не искажена, инфа 100% ))
2) ссылка в основном акке отработала как надо и активация успешна.
3) выложить сюда ссылку с хешем?

**Comment by DEgITx** [comment]
Хорошо, она уже активирована значит, можно выкладывать без риска. А что за почтовый провайдер в обоих случаях?

**Comment by Alien-ufo** [comment]
https://talkvio.com/confirmregistation/277d149681e2627b6bc4e2a116e9233d

Gmail

**Comment by DEgITx** [comment]
странно, ссылка абсолютно корректна, в любом случае должен был открыться именно сайт и выдать успешную или ошибочкую регистрацию, а выдает ли все еще 500 ошибку какого-либо аккаунта?

**Comment by Alien-ufo** [comment]
Вы точно внимательно прочитали 1й пост? )
Сейчас выдаёт 
![image](https://github.com/user-attachments/assets/548c4274-76af-4e89-93a7-c7f044c576e5)

**Comment by DEgITx** [comment]
данная ошибка корректна, это то чего я и ожидал в случае если аккаунт уже активирован, пока думаю что 500 была либо единовременной сетевой, либо некорректной ссылкой с гмыла, пока закрою этот баг, потому что не вижу что удалось его повторить - либо мне либо вам, если вдруг реально можете пересоздать или переоткрыть
