### ISSUE TITLE
Баг при смене пароля

### ISSUE THREAD

**Issue by vokdals** [Talkvio/talkvio-public#15]
Зарегистрировался с помощью Гугл аккаунт, захотел поменять парлоль на свой и не смог
(macOS 14.5 Sonoma, браузер Safari)

https://github.com/user-attachments/assets/24ee66c7-f3b8-4648-83ed-8564afaade9a

Я так понял это происходит из-за системы предложения надежного пароля. Но это не точно

**Comment by DEgITx** [comment]
Вау, спасибо, разберемся, не знал что такое на макоси поведение

**Comment by DEgITx** [comment]
в теории должно быть поправлено
