### ISSUE TITLE
Скрытие оцененных постов

### ISSUE THREAD

**Issue by mrChOP93** [Talkvio/talkvio-public#2]
Думаю, стоит добавить скрытие оцененных постов, при включении данной опции
![image](https://github.com/Talkvio/talkvio-public/assets/65346358/087d5b47-8e62-4200-8bf9-a7bccdb1db73)
![image](https://github.com/Talkvio/talkvio-public/assets/65346358/3c2b5f4c-bbe5-4427-b4a8-676e79cbf5c7)

**Comment by DEgITx** [comment]
хорошо, будет сделано

**Comment by mrChOP93** [comment]
Еще как вариант, можно добавить опцию "Сворачивать", или "Скрывать" просмотренное

**Comment by DEgITx** [comment]
Сделал, сворачивание или скрытие плиз вынеси в отдельную задачу, эту пока закрываю
