### ISSUE TITLE
Подсказка управления в ленте

### ISSUE THREAD

**Issue by mrChOP93** [Talkvio/talkvio-public#3]
Можно добавить блок с подсказкой управления клавишами в левую часть сайта
![image](https://github.com/Talkvio/talkvio-public/assets/65346358/7c42a4af-0321-47fd-9c0f-1aa81dc79b6f)

**Comment by DEgITx** [comment]
![image](https://github.com/Talkvio/talkvio-public/assets/207785/6a5651b5-4b97-4052-b39b-38f636c7f882)
вроде же есть в левой части, просто его сразу можно скрыть если не нужен

**Comment by mrChOP93** [comment]
А, точно, я же его скрыл) А как вернуть, если понадобится? Может просто его сворачивать в тонкую линию?

**Comment by DEgITx** [comment]
хм, может просто пункт в настройки добавить, типо "показывать управление клавиатурой"?

**Comment by mrChOP93** [comment]
Как вариант

**Comment by DEgITx** [comment]
сделано, вынес в настройки (как обычно нужно пообновлять страницу пару раз чтобы заработала новая версия)
